export const GET_SYMPTOM_OF_DISEASE_SUCCESS = 'GET_SYMPTOM_OF_DISEASE_SUCCESS'
export const GET_SYMPTOM_OF_DISEASE_FAIL = 'GET_SYMPTOM_OF_DISEASE_FAIL'
export const GET_SYMPTOM_OF_DISEASE_CLEAR_DATA = 'GET_SYMPTOM_OF_DISEASE_CLEAR_DATA'
