export const SET_SYMPTOM_OF_DISEASE_SUCCESS = 'SET_SYMPTOM_OF_DISEASE_SUCCESS'
export const SET_SYMPTOM_OF_DISEASE_FAIL = 'SET_SYMPTOM_OF_DISEASE_FAIL'
export const SET_SYMPTOM_OF_DISEASE_CLEAR_DATA = 'SET_SYMPTOM_OF_DISEASE_CLEAR_DATA'
